# Generated by Django 3.2 on 2023-02-27 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BLACK', 'BLACK'), ('RED', 'RED'), ('WHITE', 'WHITE'), ('BROWN', 'BROWN'), ('GREY', 'GREY'), ('YELLOW', 'YELLOW')], max_length=500)),
                ('temperature', models.IntegerField(help_text='Temperature is measured in Centigrades')),
                ('structure', models.CharField(choices=[('PLATY', 'PLATY'), ('PLISMATIC', 'PLISMATIC'), ('COLUMNAR', 'COLUMNAR'), ('GRANULAR', 'GRANULAR'), ('BLOCKY', 'BLOCKY')], max_length=500)),
                ('texture', models.CharField(choices=[('SAND', 'SAND'), ('LOAMY SAND', 'LOAMY SAND'), ('SANDY LOAM', 'SANDY LOAM'), ('LOAM', 'LOAM')], max_length=500)),
                ('porosity', models.DecimalField(decimal_places=2, help_text='Porosity is measured in g/cm**3', max_digits=3)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shamba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('soil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soil', to='mkulima.soil')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, verbose_name='Full_name')),
                ('profile_picture', models.ImageField(default='images/profile.png', upload_to='images/', verbose_name='Avatar')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('shamba', models.ManyToManyField(to='mkulima.Shamba')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mkulima', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
