# Generated by Django 3.2 on 2023-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shamba',
            field=models.ManyToManyField(null=True, to='mkulima.Shamba'),
        ),
    ]
