# Generated by Django 3.2 on 2023-02-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0003_alter_profile_shamba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='#49DIE382OZ', max_length=500, verbose_name='Full_name'),
        ),
    ]
