# Generated by Django 3.2 on 2023-03-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0004_alter_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shamba',
            field=models.ManyToManyField(blank=True, related_name='shamba', to='mkulima.Shamba'),
        ),
    ]
