# Generated by Django 3.2 on 2023-03-02 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mkulima', '0005_alter_profile_shamba'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='images/profile.png', upload_to='images/', verbose_name='Profile picture')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('ward', models.CharField(max_length=500)),
                ('street', models.CharField(help_text='Street/Village', max_length=500)),
                ('education_level', models.CharField(choices=[('BACHELOR DEGREE', 'BACHELOR DEGREE'), ('DIPLOMA', 'DIPLOMA'), ('O-LEVEL', 'O-LEVEL'), ('A-LEVEL', 'A-LEVEL')], max_length=500)),
                ('attachment', models.FileField(upload_to='images/')),
                ('user_group', models.CharField(choices=[('GATHER', 'GATHER'), ('ARGONOMIC', 'ARGONOMIC'), ('3RD PARTIES', '3RD PARTIES')], max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='argonomic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married', models.BooleanField(default=True)),
                ('noChild', models.IntegerField(blank=True, null=True)),
                ('noWives', models.IntegerField(blank=True, null=True)),
                ('nolivestock', models.IntegerField(blank=True, null=True)),
                ('houseType', models.CharField(choices=[('NYASI', 'NYASI'), ('BATI', 'BATI'), ('GOOD STANDARD', 'GOOD STANDARD')], max_length=3000)),
                ('photo', models.ImageField(upload_to='images/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftHeightContours', models.CharField(max_length=1000000000)),
                ('rightHeightContours', models.CharField(max_length=100000000)),
                ('topWidthContours', models.CharField(max_length=1000000000)),
                ('bottomWidthControus', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=8000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=8000)),
                ('nationalID', models.CharField(max_length=8000)),
                ('phone', models.CharField(max_length=15)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mkulima.familydetails')),
            ],
        ),
        migrations.CreateModel(
            name='NextKeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=2000)),
                ('age', models.CharField(max_length=2000)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('ward', models.CharField(max_length=500)),
                ('street', models.CharField(help_text='Street/Village', max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ManyToManyField(blank=True, to='mkulima.FamilyDetails')),
            ],
        ),
        migrations.CreateModel(
            name='GatherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='images/profile.png', upload_to='images/', verbose_name='Profile picture')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('ward', models.CharField(max_length=500)),
                ('street', models.CharField(help_text='Street/Village', max_length=500)),
                ('user_group', models.CharField(choices=[('GATHER', 'GATHER'), ('ARGONOMIC', 'ARGONOMIC'), ('3RD PARTIES', '3RD PARTIES')], max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gather', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GatheredInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gathered_at', models.DateTimeField(auto_now_add=True)),
                ('gathered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkulima.gatherprofile')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mkulima.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmId', models.CharField(help_text='FamilyId should be unique....', max_length=500)),
                ('current_use', models.CharField(help_text='Linatumika kufanyia nini kwa sasa', max_length=8000)),
                ('current_crop', models.CharField(blank=True, help_text='Endapo mtu atasema linalimwa inabidi tujue ni zao gani', max_length=8000, null=True)),
                ('average_yield', models.CharField(blank=True, help_text='Endapo linalimwa linatoa gunia ngapi', max_length=8000, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('farm_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mkulima.gatheredinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ArgoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleId', models.CharField(max_length=300)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('argonomist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mkulima.argonprofile')),
                ('farm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mkulima.farm')),
            ],
        ),
    ]
