# Generated by Django 3.2 on 2023-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0006_argonprofile_argoreport_familydetails_farm_gatheredinfo_gatherprofile_nextkeen_owner_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argonprofile',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('BACHELOR DEGREE', 'BACHELOR DEGREE'), ('DIPLOMA', 'DIPLOMA'), ('O-LEVEL', 'O-LEVEL'), ('A-LEVEL', 'A-LEVEL')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='images/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='region',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='street',
            field=models.CharField(blank=True, help_text='Street/Village', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='user_group',
            field=models.CharField(blank=True, choices=[('GATHER', 'GATHER'), ('ARGONOMIC', 'ARGONOMIC'), ('3RD PARTIES', '3RD PARTIES')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gatherprofile',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gatherprofile',
            name='district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gatherprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gatherprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gatherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='gatherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='images/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='gatherprofile',
            name='region',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gatherprofile',
            name='street',
            field=models.CharField(blank=True, help_text='Street/Village', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gatherprofile',
            name='user_group',
            field=models.CharField(blank=True, choices=[('GATHER', 'GATHER'), ('ARGONOMIC', 'ARGONOMIC'), ('3RD PARTIES', '3RD PARTIES')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gatherprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
