# Generated by Django 3.2 on 2023-03-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0007_auto_20230302_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='argonprofile',
            name='profileIsCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatherprofile',
            name='profileIsCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
