# Generated by Django 3.2 on 2023-03-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0008_auto_20230302_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argonprofile',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
