# Generated by Django 3.2 on 2023-03-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0009_alter_argonprofile_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argonprofile',
            name='education_level',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='argonprofile',
            name='user_group',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
