# Generated by Django 3.2 on 2023-03-03 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0012_auto_20230303_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='soil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smetadata', to='mkulima.soilmetadata'),
        ),
    ]
