# Generated by Django 3.2 on 2023-03-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0013_alter_farm_soil'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=50)),
                ('soil_color', models.CharField(max_length=200)),
                ('soil_temperature', models.IntegerField(help_text='Temperature is measured in Centigrades')),
                ('soil_structure', models.CharField(max_length=500)),
                ('soil_texture', models.CharField(max_length=500)),
                ('soil_porosity', models.DecimalField(decimal_places=2, help_text='Porosity is measured in g/cm**3', max_digits=3)),
                ('soil_ph', models.DecimalField(decimal_places=1, help_text='pH is decimal/number', max_digits=3)),
                ('soil_form', models.CharField(max_length=200)),
                ('bulk_density', models.DecimalField(decimal_places=5, help_text='Bulk density we measure in kg/m3', max_digits=10)),
                ('soil_moisture', models.IntegerField(help_text='measured in water fraction by volute m3m-3')),
                ('phosphorus_level', models.IntegerField(help_text='measured in ppm-parts per millions')),
                ('potassium_level', models.IntegerField(help_text='measured in ppm-parts per millions')),
                ('nitrogen_level', models.IntegerField(help_text='measured in ppm-parts per milliions')),
                ('organic_matter', models.IntegerField(help_text='measured in t/ha tonne per hectare')),
            ],
        ),
        migrations.RemoveField(
            model_name='farm',
            name='soil',
        ),
        migrations.AddField(
            model_name='argoreport',
            name='recommendation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='argoreport',
            name='test_results',
            field=models.OneToOneField(default='1232', on_delete=django.db.models.deletion.CASCADE, related_name='testresults', to='mkulima.testresult'),
        ),
    ]
