# Generated by Django 3.2 on 2023-03-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0015_alter_argoreport_test_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argoreport',
            name='recommendation',
            field=models.TextField(),
        ),
    ]
