# Generated by Django 3.2 on 2023-03-03 14:40

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0016_alter_argoreport_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='argoreport',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='argoreport',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 14, 40, 49, 325816)),
        ),
    ]
