# Generated by Django 3.2 on 2023-03-03 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0017_auto_20230303_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argoreport',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 14, 41, 17, 560143)),
        ),
        migrations.AlterField(
            model_name='argoreport',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
