# Generated by Django 3.2 on 2023-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0018_auto_20230303_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argoreport',
            name='added_on',
            field=models.DateTimeField(),
        ),
    ]
