# Generated by Django 3.2 on 2023-03-03 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0020_auto_20230303_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheredinfo',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 16, 37, 35, 608000)),
        ),
        migrations.AlterField(
            model_name='gatheredinfo',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 16, 37, 35, 608022)),
        ),
        migrations.AlterField(
            model_name='gatheredinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
