# Generated by Django 3.2 on 2023-03-03 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0021_auto_20230303_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheredinfo',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 16, 38, 10, 913261)),
        ),
        migrations.AlterField(
            model_name='gatheredinfo',
            name='locked_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 16, 38, 10, 913282)),
        ),
    ]
