# Generated by Django 3.2 on 2023-03-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0024_auto_20230303_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheredinfo',
            name='assigned_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gatheredinfo',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
