# Generated by Django 3.2 on 2023-03-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0025_auto_20230303_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familydetails',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='nextkeen',
            name='street',
        ),
        migrations.AddField(
            model_name='nextkeen',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='country',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='district',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='region',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='ward',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
