# Generated by Django 3.2 on 2023-03-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0026_auto_20230303_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='country',
            field=models.CharField(default='...llk', max_length=500),
        ),
        migrations.AlterField(
            model_name='owner',
            name='district',
            field=models.CharField(default='...llk', max_length=500),
        ),
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(default='...llk', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='region',
            field=models.CharField(default='...llk', max_length=500),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ward',
            field=models.CharField(default='...llk', max_length=500),
        ),
    ]
