# Generated by Django 3.2 on 2023-03-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0028_auto_20230303_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextkeen',
            name='photo',
            field=models.ImageField(default='dkldl', upload_to='images/'),
        ),
    ]
