# Generated by Django 3.2 on 2023-03-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0029_alter_nextkeen_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextkeen',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
