# Generated by Django 3.2 on 2023-03-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0030_alter_nextkeen_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextkeen',
            name='street',
            field=models.CharField(blank=True, help_text='Street/Village', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='street',
            field=models.CharField(blank=True, help_text='Street/Village', max_length=500, null=True),
        ),
    ]
