# Generated by Django 3.2 on 2023-03-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0034_gatheredinfo_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextkeen',
            name='age',
            field=models.IntegerField(),
        ),
    ]
