# Generated by Django 3.2 on 2023-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0035_alter_nextkeen_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheredinfo',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
