# Generated by Django 3.2 on 2023-03-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0036_alter_gatheredinfo_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheredinfo',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
