# Generated by Django 3.2 on 2023-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0037_alter_gatheredinfo_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farmId',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farm_metadata',
        ),
        migrations.AlterField(
            model_name='farm',
            name='average_yield',
            field=models.TextField(blank=True, help_text='Endapo linalimwa linatoa gunia ngapi', null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='current_crop',
            field=models.TextField(blank=True, help_text='Endapo mtu atasema linalimwa inabidi tujue ni zao gani', max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='current_use',
            field=models.TextField(help_text='Linatumika kufanyia nini kwa sasa'),
        ),
    ]
