# Generated by Django 3.2 on 2023-03-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0039_farm_farm_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gatheredinfo', to='mkulima.gatheredinfo'),
        ),
    ]
