# Generated by Django 3.2 on 2023-03-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0040_alter_farm_farm_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextkeen',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
