# Generated by Django 3.2 on 2023-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0041_nextkeen_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familydetails',
            name='married',
        ),
        migrations.AddField(
            model_name='familydetails',
            name='martial_status',
            field=models.CharField(default='Married', max_length=200),
        ),
    ]
