# Generated by Django 3.2 on 2023-03-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0043_auto_20230308_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheredinfo',
            name='assignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignedto', to='mkulima.argonprofile'),
        ),
    ]
