# Generated by Django 3.2 on 2023-03-09 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0044_alter_gatheredinfo_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheredinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_owner', to='mkulima.owner'),
        ),
    ]
