# Generated by Django 3.2 on 2023-03-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0045_alter_gatheredinfo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='argoreport',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
