# Generated by Django 3.2 on 2023-03-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0046_argoreport_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argoreport',
            name='argonomist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='argoreport', to='mkulima.argonprofile'),
        ),
    ]
