# Generated by Django 3.2 on 2023-03-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0047_alter_argoreport_argonomist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argoreport',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mkulima.farm'),
        ),
    ]
