# Generated by Django 3.2 on 2023-03-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0048_alter_argoreport_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatheredinfo',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='gatheredinfo',
            name='locked_at',
        ),
    ]
