# Generated by Django 3.2 on 2023-03-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0049_auto_20230310_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='leftHeightContours',
            new_name='allCoords',
        ),
        migrations.RemoveField(
            model_name='size',
            name='bottomWidthControus',
        ),
        migrations.RemoveField(
            model_name='size',
            name='rightHeightContours',
        ),
        migrations.RemoveField(
            model_name='size',
            name='topWidthContours',
        ),
    ]
