# Generated by Django 3.2 on 2023-03-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0050_auto_20230310_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='argoreport',
            name='is_completed_and_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
