# Generated by Django 3.2 on 2023-03-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0054_alter_argoreport_sampleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argoreport',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
