# Generated by Django 3.2 on 2023-03-13 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0056_auto_20230313_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soil',
            name='porosity',
        ),
        migrations.AlterField(
            model_name='argoreport',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='mkulima.farm'),
        ),
    ]
