# Generated by Django 3.2 on 2023-03-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0057_auto_20230313_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='testresult',
            name='soil_porosity',
            field=models.CharField(blank=True, help_text='Porosity is measured in kg/m**3', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='wards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('district_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mkulima.districts')),
            ],
        ),
        migrations.AddField(
            model_name='districts',
            name='region_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mkulima.regions'),
        ),
    ]
