# Generated by Django 3.2 on 2023-03-13 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0059_auto_20230313_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districts',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkulima.regions'),
        ),
        migrations.AlterField(
            model_name='wards',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mkulima.districts'),
        ),
    ]
