# Generated by Django 3.2 on 2023-03-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0063_alter_adminprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='name',
            field=models.CharField(blank=True, default='#7323D923', max_length=50, null=True),
        ),
    ]
