# Generated by Django 3.2 on 2023-03-19 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0068_auto_20230319_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='argoreport',
            name='recommendation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mkulima.recommendations'),
        ),
    ]
