# Generated by Django 3.2 on 2023-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0069_argoreport_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendations',
            old_name='fertilizers',
            new_name='fertilizer_name',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='amount_of_fertilizer',
            field=models.CharField(blank=True, help_text='Ujazo wa mbolea unaohitajika kutumia', max_length=800, null=True),
        ),
    ]
