# Generated by Django 3.2 on 2023-03-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0070_auto_20230319_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argoreport',
            name='recommendation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fullreport', to='mkulima.recommendations'),
        ),
    ]
