# Generated by Django 3.2 on 2023-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0073_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
