# Generated by Django 3.2 on 2023-05-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0074_auto_20230430_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='argonprofile',
            name='user_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gatherprofile',
            name='user_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
