# Generated by Django 3.2 on 2023-05-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkulima', '0076_alter_owner_nationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextkeen',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
