"""
Django settings for MkulimaBackend project.

Generated by 'django-admin startproject' using Django 3.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from django.urls import reverse_lazy
from pathlib import Path
import os
import sys
from datetime import timedelta
import os.path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pt1br&!vqa4%txy7(on@rmpkn&i56sni_@cc#5w(2*_-lo%a97'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'MkulimaBackend.register',
    'MkulimaBackend.api',
    'MkulimaBackend.mkulima',
    'MkulimaBackend.argonomist',
    'MkulimaBackend.administrator',
    'MkulimaBackend.gatherman',
    'rest_framework',
    'corsheaders',
    'whitenoise.runserver_nostatic',
    'rest_framework_simplejwt.token_blacklist',
    # 'postmark', # Google inasumbua ko lipia postmarker since it's made for this issues of mail seding
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MkulimaBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['%s/templates/' % (PROJECT_DIR)],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MkulimaBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'GMT'... To get all timezones code like this of 'Africa/Dar_es_Salaam' do
# print(pytz.all_timezones).. by default if your system used across globe use UTC timezone
# which is not corrent in given country but you can convert it to given country from UTC...
# Give thanks to this https://stackoverflow.com/questions/27182557/valueerror-incorrect-timezone-setting-while-migrating-manage-py-file-in-django
# https://www.freecodecamp.org/news/how-to-get-the-current-time-in-python-with-datetime/
# https://www.youtube.com/watch?v=5u9V5XulvqI
# TIME_ZONE = 'UTC
TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_L10N = True

USE_TZ = True


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]


STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# SMTP Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# make sure you logged in using this account before using this service otherwise you will get this error 'socket.gaierrorsocket.gaierror: [Errno -2] Name or service not known'
EMAIL_HOST_USER = 'paschalnzwanga2015@gmail.com'
EMAIL_HOST_PASSWORD = 'lchobawtmrxfcsjm'
'''
    YOU NEED TO PUT THE APP PASSWORD AND DON'T DELETE IT...HERE THIS APP PASSWORD SHOULD EXIST IN YOUR
    EMAIL AND YOU SHOULD ALLOW 2WAY VERIFICATION... HERE THERE IS OTHER ALTENATIVE FOR GMAIL IF THERE IS 
    PROBLEMS IN SENDING MAILS BUT IN MOST CASE IF YOU HAVE 2-WAYS VERIFICATION AND YOU HAVE THE
    THIS APP PASSWORD EXISTED THE EMAIL WILL WORK FINE THE APP PASSWORD CAN BE SETTED IN 2-WAYS VERIFICATION
    SECTION... UNAJUA NILIKUWA NAKOSEA MPAKA NIKAHISI BASI GMAIL HAIWEZI KU-SEND THE VERIFICATION CODE MPAKA
    NIKAKATA TAMAAA... KUNA FAIDA COZ NILIJARIBU KUTAFUTA OTHER ALTENATIVE WHICH IS 'postmark' 
    https://account.postmarkapp.com/api_tokens .. THE WAY TO LINK WITH DJANGO EXPLAINED HERE 
    https://pypi.org/project/django-postmark/ .... BUT HII POSTMARK NI HATARI NA INA-ADVANCED FEATURES KO
    INABIDI ULIPIE... MI SINA HUO UWEZO KO CHA MUHIMU NI KU-KEEP UP WITH THIS GMAIL SMTP... NOW EVERYTHING
    WORKED FINE.. THANKS YOU GOD... BUT FOR ANY CASE ON SETTING THIS 'postmark' YOU CAN GO TO THIS LARAVEL 
    HOW TO LINK POSTMARK VIDEO https://youtu.be/O-t3kNiXxIc ... postmark ni wazuri ila hawa jamaa wanataka 
    ujisajili kupitia ur organization email/domain without hii uwezi ila mimi coz nina email ya 
    mainstream kwangu imekua rahisi na nimejisajili kupitia paschal.nzwanga@mainstreammedia.co.tz  
'''


AUTH_USER_MODEL = 'register.CustomUser'

LOGIN_URL = reverse_lazy('login')
